version: '3'

services:

  # docker-compose run ansible /ansible/install.sh 
  ansible:
    build:
      args:
        - IMAGE=${IMAGE}
        - WORKDIR=${WORKDIR}
      context: .
      dockerfile: Dockerfile
    image: cloudlife/ansible
    volumes:
      - ".:${WORKDIR}"
      - "~/.ansible:/root/.ansible"
    working_dir: ${WORKDIR}